import { ReactElement } from 'react'

export const paises = [
    'México',
    'Estados Unidos',
    'Canadá',
    'Afganistán',
    'Albania',
    'Alemania',
    'Andorra',
    'Angola',
    'Antigua y Barbuda',
    'Arabia Saudita',
    'Argelia',
    'Argentina',
    'Armenia',
    'Australia',
    'Austria',
    'Azerbaiyán',
    'Bahamas',
    'Bangladés',
    'Barbados',
    'Baréin',
    'Bélgica',
    'Belice',
    'Benín',
    'Bielorrusia',
    'Birmania',
    'Bolivia',
    'Bosnia y Herzegovina',
    'Botsuana',
    'Brasil',
    'Brunéi',
    'Bulgaria',
    'Burkina Faso',
    'Burundi',
    'Bután',
    'Cabo Verde',
    'Camboya',
    'Camerún',
    'Catar',
    'Chad',
    'Chile',
    'China',
    'Chipre',
    'Ciudad del Vaticano',
    'Colombia',
    'Comoras',
    'Corea del Norte',
    'Corea del Sur',
    'Costa de Marfil',
    'Costa Rica',
    'Croacia',
    'Cuba',
    'Dinamarca',
    'Dominica',
    'Ecuador',
    'Egipto',
    'El Salvador',
    'Emiratos Árabes Unidos',
    'Eritrea',
    'Eslovaquia',
    'Eslovenia',
    'España',
    'Estonia',
    'Etiopía',
    'Filipinas',
    'Finlandia',
    'Fiyi',
    'Francia',
    'Gabón',
    'Gambia',
    'Georgia',
    'Ghana',
    'Granada',
    'Grecia',
    'Guatemala',
    'Guyana',
    'Guinea',
    'Guinea ecuatorial',
    'Guinea-Bisáu',
    'Haití',
    'Honduras',
    'Hungría',
    'India',
    'Indonesia',
    'Irak',
    'Irán',
    'Irlanda',
    'Islandia',
    'Islas Marshall',
    'Islas Salomón',
    'Israel',
    'Italia',
    'Jamaica',
    'Japón',
    'Jordania',
    'Kazajistán',
    'Kenia',
    'Kirguistán',
    'Kiribati',
    'Kuwait',
    'Laos',
    'Lesoto',
    'Letonia',
    'Líbano',
    'Liberia',
    'Libia',
    'Liechtenstein',
    'Lituania',
    'Luxemburgo',
    'Macedonia del Norte',
    'Madagascar',
    'Malasia',
    'Malaui',
    'Maldivas',
    'Malta',
    'Marruecos',
    'Mauricio',
    'Mauritania',
    'Micronesia',
    'Moldavia',
    'Mónaco',
    'Mongolia',
    'Montenegro',
    'Mozambique',
    'Namibia',
    'Nauru',
    'Nepal',
    'Nicaragua',
    'Níger',
    'Nigeria',
    'Noruega',
    'Nueva Zelanda',
    'Omán',
    'Países Bajos',
    'Pakistán',
    'Palaos',
    'Panamá',
    'Papúa Nueva Guinea',
    'Paraguay',
    'Perú',
    'Polonia',
    'Portugal',
    'Reino Unido',
    'República Centroafricana',
    'República Checa',
    'República del Congo',
    'República Democrática del Congo',
    'República Dominicana',
    'República Sudafricana',
    'Ruanda',
    'Rumanía',
    'Rusia',
    'Samoa',
    'San Cristóbal y Nieves',
    'San Marino',
    'San Vicente y las Granadinas',
    'Santa Lucía',
    'Santo Tomé y Príncipe',
    'Senegal',
    'Serbia',
    'Seychelles',
    'Sierra Leona',
    'Singapur',
    'Siria',
    'Somalia',
    'Sri Lanka',
    'Suazilandia',
    'Sudán',
    'Sudán del Sur',
    'Suecia',
    'Suiza',
    'Surinam',
    'Tailandia',
    'Tanzania',
    'Tayikistán',
    'Timor Oriental',
    'Togo',
    'Tonga',
    'Trinidad y Tobago',
    'Túnez',
    'Turkmenistán',
    'Turquía',
    'Tuvalu',
    'Ucrania',
    'Uganda',
    'Uruguay',
    'Uzbekistán',
    'Vanuatu',
    'Venezuela',
    'Vietnam',
    'Yemen',
    'Yibuti',
    'Zambia',
    'Zimbabue',
]

export const estados = [
    'Aguascalientes',
    'Baja California',
    'Baja California Sur',
    'Campeche',
    'Chiapas',
    'Chihuaha',
    'Ciudad de México',
    'Coahuila',
    'Colima',
    'Durango',
    'Guanajuato',
    'Guerrero',
    'Hidalgo',
    'Jalisco',
    'México',
    'Michoacán',
    'Morelos',
    'Nayarit',
    'Nuevo León',
    'Oaxaca',
    'Puebla',
    'Querétaro',
    'Quintana Roo',
    'San Luis Potosí',
    'Sinaloa',
    'Sonora',
    'Tabasco',
    'Tamaulipas',
    'Tlaxcala',
    'Veracruz',
    'Yucatán',
    'Zacatecas',
]

export const estudios = [
    'Sin estudios',
    'Primaria incompleta',
    'Primaria concluida',
    'Secundaria incompleta',
    'Secundaria concluida',
    'Carrera técnica',
    'Bachillerato incompleto',
    'Bachillerato concluido',
    'Técnico superior universitario',
    'Licenciatura incompleta',
    'Licenciatura concluida',
    'Especialidad',
    'Maestría',
    'Doctorado',
    'Otro',
]

export const ocupaciones = [
    'Selecciona una ocupación',
    'Trabajador/a de campo',
    'Ama/o de casa',
    'Pensionado/a o Jubilado/a',
    'Maestro/a',
    'Doctor/a',
    'Enfermero/a',
    'Ingeniero/a',
    'Abogado/a',
    'Trabajador/a de gobierno',
    'Arquitecto/a',
    'Policia',
    'Otra',
]

export const ingresos = [
    'Selecciona el ingreso mensual',
    'Hasta 2 000',
    'De 2 001 a 6 000',
    'De 6 001 a 10 000',
    'De 10 001 a 20 000',
    'De 20 001 a 30 000',
    'Más de 30 000',
    'Sin ingresos',
]

export const unoSeis = ['Ninguno', '1', '2', '3', '4', '5', '6 o más']

export const gruposIndigenas = [
    'Selecciona el grupo indígena',
    'Mixteco',
    'Triqui',
    'Zapoteco',
    'Huasteco',
    'Maya',
    'Mazateco',
    'Nahualt',
    'Otomí',
    'Purépecha',
    'Totonaca',
    'Otro',
]

export const delegaciones = [
    'Selecciona la delegación',
    'San Vicente',
    'Colonet',
    'Camalú',
    'Vicente Guerrero',
    'San Quintín',
    'El Rosario',
    'Bahía de los Angeles',
]

export const horas = [
    '00:00',
    '00:30',
    '01:00',
    '01:30',
    '02:00',
    '02:30',
    '03:00',
    '03:30',
    '04:00',
    '04:30',
    '05:00',
    '05:30',
    '06:00',
    '06:30',
    '07:00',
    '07:30',
    '08:00',
    '08:30',
    '09:00',
    '09:30',
    '10:00',
    '10:30',
    '11:00',
    '11:30',
    '12:00',
    '12:30',
    '13:00',
    '13:30',
    '14:00',
    '14:30',
    '15:00',
    '15:30',
    '16:00',
    '16:30',
    '17:00',
    '17:30',
    '18:00',
    '18:30',
    '19:00',
    '19:30',
    '20:00',
    '20:30',
    '21:00',
    '21:30',
    '22:00',
    '22:30',
    '23:00',
    '23:30',
]

export const numeroDias = ['Selecciona los días', '1 Día', '2 Días', '3 Días', '4 Días', '5 Días', '6 Días', '7 Días']

export const serviciosMedicosData = [
    'NO CUENTO CON OTROS SERVICIOS MÉDICOS',
    'IMSS',
    'ISSSTE',
    'ISSSTECALI',
    'SEGURO POPULAR',
    'PEMEX',
    'EJERCITO/MARINA',
    'SECRETARIA DE SALUD',
    'IMSS OPORTUNIDADES',
    'MEDICO PRIVADO',
    'OTRO',
]

export const frecuenciaAsistenciaMedicoData = ['Cada semana', 'Cada mes', 'Cada seis meses', 'Cada año', 'Cuando me enfermo']

export const frecuenciaAsistenciaDentistaData = ['Cada semana', 'Cada mes', 'Cada seis meses', 'Cada año', 'Cuando lo necesito']

export const necesitoLentesData = ['No los necesito', 'Sólo para leer', 'Sí, los uso', 'Sí, los necesito pero no los uso', 'No lo sé']

export const tratamientoMentalData = ['Selecciona cuantas veces', '1-3 veces', '4-6 veces', '7-9 veces', '10-12 veces', '13 o más']

export const tiposAlergiasData = [
    'Seleccione un tipo de alergia',
    'Farmacológica',
    'A alimentos',
    'Dermatitis de contacto',
    'Alergia al látex',
    'Asma alérgica',
    'Rinitis alergica',
    'A animales',
    'Anafilaxia',
    'Al moho',
    'Otra',
]

export const carreras = [
    'Selecciona una carrera',
    'TÉCNICO AGROPECUARIO',
    'TÉCNICO EN OFIMÁTICA',
    'TÉCNICO EN SISTEMAS DE PRODUCCIÓN AGRÍCOLA',
    'TÉCNICO EN SISTEMAS DE PRODUCCIÓN PECUARIA',
    'TÉCNICO EN PRODUCCIÓN INDUSTRIAL DE ALIMENTOS',
    'TÉCNICO EN ADMINISTRACIÓN PARA EL EMPRENDIMIENTO AGROPECUARIO',
]
