export { DatosPersonales } from './DatosPersonales'
export { DatosPadre } from './DatosPadre'
export { DatosMadre } from './DatosMadre'
export { DatosContacto } from './DatosContacto'
export { PuntosTutor } from './PuntosTutor'
export { DatosFamiliares } from './DatosFamiliares'
export { FamiliarOption } from './FamiliarOption'
